
name-template: 'Ramoloss v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Fonctionnalités'
    labels:
      - 'feature'
  - title: '🔧 Bug'
    labels:
      - 'bug'
  - title: '📖 Documentation'
    labels:
      - 'doc'

autolabeler:
  - label: 'doc'
    files:
      - '*.md'
    branch:
      - '/docs\/.+'
  - label: 'bug'
    branch:
      - '/fix\/.+'
  - label: 'enh'
    branch:
      - '/feat\/.+/'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Changements

  $CHANGES

