version: "3.9"

services:
  bot:
      environment:
        - DISCORD_TOKEN=${DISCORD_TOKEN}
      container_name: ${APP_NAME}
      image: ${APP_NAME}
      build:
          context : .
          dockerfile: Dockerfile.${ARCH}
