version: '3.9'
services:
  bot:
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    container_name: ${NAME}-bot
    image: ${NAME}-bot:${VERSION}
    build:
        context : .
        dockerfile: Dockerfile.${ARCH}
