FROM python:3.10-buster as x86_64
RUN useradd -ms /bin/bash bot
USER bot
ENV DISCORD_TOKEN=${DISCORD_TOKEN}
WORKDIR /ramoloss
COPY . .
RUN apt-get update && pip install --no-cache-dir -e bot/
CMD [ "python", "main.py"]

