name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # action by user
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ARCH: armv7l
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
          - ARCH: x86_64
            registry: docker.io
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to ${{ matrix.registry }}
        id: ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ matrix.username }}
          password: ${{ matrix.password }}

      - name: Build and test on ${{ matrix.ARCH }} plateform
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_DEV_TOKEN }}
        run:
          ci/run-test.sh

      - name: build with cache and push on registry if success
        if: ( success() && github.ref == 'refs/heads/main' )
        run: |

          #ghcr.io/${{ github.actor }}/${APP}:latest
