name: Continious integration

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DISCORD_DEV_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true
      NAME_OWNER:
        required: true
    input:
        VERSION:
          required: false
          type: string

  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ARCH: armv7l
            registry: ghcr.io
            username: NAME_OWNER
            password: GITHUB_TOKEN
          - ARCH: x86_64
            registry: docker.io
            username: DOCKERHUB_USERNAME
            password: DOCKERHUB_TOKEN
    name: build ${{ matrix.ARCH }}

    steps:
      - name: Prepare before build
        run: |
          sudo apt-get update -y

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to ${{ matrix.registry }}
        uses: docker/login-action@v1
        with:
          registry: ${{ matrix.registry }}
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}

      - name: Build and test on ${{ matrix.ARCH }} plateform
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_DEV_TOKEN }}
        run: |
          bash ci/build.sh

      - name: push on ${{ matrix.registry }} if success on main branch
        if: ( success() && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
        env:
          ARCH: ${{ matrix.ARCH }}
          REGISTRY: ${{ matrix.registry }}
          REGISTRY_USERNAME: ${{ secrets[matrix.username] }}
        run: |
          bash ci/push.sh

