name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # action by user
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ARCH: armv7l
            registry: ghcr.io
            username: NAME_OWNER
            password: GITHUB_TOKEN
          - ARCH: x86_64
            registry: docker.io
            username: DOCKERHUB_USERNAME
            password: DOCKERHUB_TOKEN
    name: build ${{ matrix.ARCH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to ${{ matrix.registry }}
        uses: docker/login-action@v1
        with:
          registry: ${{ matrix.registry }}
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}

      - name: Build and test on ${{ matrix.ARCH }} plateform
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_DEV_TOKEN }}
        run: |
          bash ci/run-build.sh

      - name: build with cache and push on registry if success
        if: ( success() && github.ref == 'refs/heads/main' )
        run: |
          #ghcr.io/${{ github.actor }}/${APP}:latest
