name: Release

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: ./.github/workflows/main.yml@main
      env:
        VERSION: latest

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Publish release
        uses: StuYarrow/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}

