name: Release

on:
  release:
    types:
      - published

jobs:
  build:
      uses: titigmr/ramoloss/.github/workflows/main.yml@main
      secrets:
        DISCORD_DEV_TOKEN: ${{ secrets.DISCORD_DEV_TOKEN }}
        DOCKERHUB_TOKEN : ${{ secrets.DOCKERHUB_TOKEN }}
        DOCKERHUB_USERNAME : ${{ secrets.DOCKERHUB_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NAME_OWNER: ${{ secrets.NAME_OWNER }}
      with:
        VERSION: latest

  release:
    needs: build
    name: Create release branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set output current version
        id: version
        run: |
          echo "::set-output name=version::$(make check-var-VERSION)"

      - name: Publish release
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-${{ steps.version.outputs.version }}'

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
